# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d1bf0adbcd54108084aa153baf44dfe595458887107a890084308aa9b0fa27c8c2d5045a3782cd0fb181cbda22e767dc3cc31ef5cb96ab90b1ab408c8d018b5

test:
  secret_key_base: 27bfd21d66cc0c72aef678b42619119e3339807e12709b5bb95c0322a28768c52dc46ebfb5a9dadc48f28ead84a0b23c1bf3ac80cd155d5ef6b3498a2f18564c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
